# -*- coding: utf-8 -*-
"""Mandatory Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/174RHniFRXyE4wCJ3PDThFHhtjc0fCTZv

# python
"""

print("Basic python on 12/07/2023 at 11:50PM")

"""The most commonly used Programming Languages for Machine Learning are:
1.Python
2.R
"""

#print
print("machine learning") #string should have "" or ''
print(8)

"""#basic data types
1.int
2.float
3.str
"""

#basic data types 1.int 2.float 3.str
a=10
b=10.3
c='hello'
d=True
e=1+2j
print(type(a),type(b),type(c),type(d),type(e))

"""#Constants and Variables"""

my_name = 'prasanth_malla'
print (my_name)

my_name='malla_prasanth'
print(my_name)

name1,name2,name3='prasanth',' naidu','malla '
print('my name is '+name3+name1+name2)

x=y=z=1

print(x+y+z)

"""#Input Function"""

number1 = input('enter the 1st number ')
print(number1)

#adding 2 numbers
a=input()
b=input()
sum = a+b
print(sum)#input function always assumes the input value as a string ,
          # so we need to convvert it to integer or required type

#we can use int(input()) to take integer value inputs
a = int(input("enter value of a"))
b = int(input("enter value of b"))
sum = a+b
print(sum)#input function always assumes the input value as a string ,
          # so we need to convvert it to integer or required type

num = 5
fb=float(num)
print(fb)

"""#Lists"""

#list
a = [1,2,3,4,5]
print(type(a))

a

#list can have multiple data types
b = [1,2,3.3,4+1j]
b

#lists are mutable
#adding elements to the list
a = [1,2,3,4,5]
a.append(1)
print(a)

#print elements  of lists using index
a=[1,2,3,4,5,5,4,3,2,1]
print(a[0],a[1:3:1],a[::-1])
#lists can have duplicate values

#length of lists
print(len(a))

#initializing the empty list
b=[8,9]
b.append(9)
print(b)

#delete an item in a list
del b[0]
print (b)

#join 2 lists
c=a+b
print(c)

"""#Tuple"""

#tuple is same as list but immutable
my_list=[1,2,3]
my_tuple=tuple(my_list)
print(my_tuple)

len(my_tuple)

"""#Set"""

my_set ={1,2,3,"hai"}
print(my_set) #set and tuple cant call elements with their index values

#convert a list to a set
list_5 = [1,2,3,4,5]
x=set(list_5)

print(x)

"""#Dictionary"""

# key value pair
my_dict={"hello":1,"hai":2}
my_dict["hello"] #set and dictonary doesn't allow duplicate values

"""#Operators in python

1. Arithmetic Operators
2. Assignment Operators
3. Comparison Operators
4. Logical Operators
5. Identity Operators
6. Membership Operators
"""

#arithmetic Operators
a=10
b=20
sum=a+b
sub=a-b
mul=a*b
div=a/b
modulo=a%b
expo = a**b
print(a,b,sum,sub,mul,div,modulo, expo)

#assignment Operators
a=12
a+=5
a-=5
a*=3
a/=2
a%=2
a

#comparison Operators
a=5
b=10
print(a==6)
print(a==b)
print(a<=b,a>=b,a<b,a>b)

#Logical Operators
#and or not
print(True and True,True and False,False and False)
print(True or False,True or True, False or False)
print(not True,not False)

#Identity Operaator
#is and is not
x=1
y=3
print(x is y)
print(x is not y)

#Member ship Operator
a = 5
b=10
c=[1,2,3,4,5,6]
print(a in c,a not in c, b in c, b not in c)

"""#If Else Statements"""

a = 10
b = 9
if a == 10 :
  print ('hello')
elif a == 9:
  print("no")

"""#Loops in Python"""

for i in range(5):
  print(i)

number = [50,100,90]
print(number)
for i in range(3):
  print(number[i])

i = 0
while i <= 3:
    print(i)
    i += 1

"""#Functions"""

#Factorial

def factorials(n):
  factorial = 1
  for i in range(1,n+1):
    factorial = i*factorial
  return factorial
factorials(5)

